name: check-codestyle
on:
  push:
  pull_request:

jobs:
  check-codestyle:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    name: check codestyle
    steps:
      - uses: actions/checkout@v2
      - name: Check core codestyle
        run: source ./apps/ci/ci-codestyle.sh

  push-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Check ./src
      run: |
        cd ./src
        find -name '*.cpp' -or -name '*.h' -print0 | xargs -r0 sed -e 's/[[:blank:]]\+$//' -i
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch --unshallow origin ${BRANCH}
        git add -A .
        git commit -am "Del w" -m "SHA: ${GITHUB_SHA}" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
